Align class and property descriptions with the new DCAT scope
SEMICeu/GeoDCAT-AP pull request #42
Opened 2020-11-28 00:26 UTC by andrea-perego

Preview: 
- [Mandatory classes](https://raw.githack.com/SEMICeu/GeoDCAT-AP/fix-issue-36/drafts/latest/index.html#mandatory-classes)

2020-12-02 15:21 UTC, bertvannuffelen commented on drafts/latest/tables/optional-properties-for-data-service.html
> +<p>This property refers to the minimum spatial separation resolvable in a Data Service, measured in metres.</p>
typo: should stay meters.

2020-12-02 15:22 UTC, bertvannuffelen commented on drafts/latest/tables/optional-properties-for-dataset.html
> +<p>This property refers to the minimum spatial separation resolvable in a Dataset, measured in metres.</p>
typo: same here meters is ok.

2020-12-02 15:22 UTC, bertvannuffelen commented on drafts/latest/tables/optional-properties-for-distribution.html
> +<p>This property refers to the minimum spatial separation resolvable in a Distribution, measured in metres.</p>
typo also here: meters

2020-12-02 15:24 UTC, bertvannuffelen requested changes
most is fine: only a typo has been introduce meters -> metres. Should stay meters.

2020-12-02 18:34 UTC, andrea-perego commented
> most is fine: only a typo has been introduce meters -> metres. Should stay meters.

This was meant to use the British English form, consistently with the rest of the document (DCAT2 uses American English instead).

2020-12-03 09:28 UTC, bertvannuffelen commented
Hi Andrea,

ok, I did not know this was an American/British english spelling issue.

kr,

Bert

Op wo 2 dec. 2020 om 19:35 schreef Andrea Perego <notifications@github.com>:

> most is fine: only a typo has been introduce meters -> metres. Should stay
> meters.
>
> This was meant to use the British English form, consistently with the rest
> of the document (DCAT2 uses American English instead).
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/SEMICeu/GeoDCAT-AP/pull/42#issuecomment-737416138>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAPIC3KK7WCRON3LXLCJ4ZTSS2CFLANCNFSM4UFNMEDQ>
> .
>

2020-12-03 19:58 UTC, andrea-perego commented
My fault, @bertvannuffelen . I should have explained it in the comments.

2020-12-04 11:30 UTC, bertvannuffelen commented
@andrea-perego ok to merge it.

2020-12-04 11:47 UTC, andrea-perego commented
Thanks, @bertvannuffelen .

2020-12-04 11:49 UTC, merged